import { Question } from './questions';

export const ALL_QUESTIONS: Question[] = [
  {
    Question_Number: 1,
    Question_ID: "UK8295094",
    Question_Text: "Given code: public class Test { public static void main(String[] args) { byte b1 = (byte) (127 + 21); System.out.println(b1); } } What is the result?",
    Option_A: "148",
    Option_B: "Compilation error",
    Option_C: "-108",
    Option_D: "128",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 2,
    Question_ID: "UK8291966",
    Question_Text: "Consider below code: public class Test { public static void main(String[] args) { char c = 'Z'; long l = 100_00l; int i = 9_2; float f = 2.02f; double d = 10_0.35d; l = c + i; f = c * l * i * f; f = l + i + c; i = (int)d; f = (long)d; } } Does above code compile successfully?",
    Option_A: "Yes",
    Option_B: "No",
    Option_C: "",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 3,
    Question_ID: "UK8298118",
    Question_Text: "Consider below code: package com.examtest.ocp; public class Test { public static void main(String[] args) { char c1 = 'a'; int i1 = c1; System.out.println(i1); } } What is the result?",
    Option_A: "a",
    Option_B: "97",
    Option_C: "Line n1 causes compilation failure",
    Option_D: "Line n1 causes runtime error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 4,
    Question_ID: "UK8291961",
    Question_Text: "Consider below statements: 1. int x = 5____0; 2. int y = ____50; 3. int z = 50____; 4. float f = 123.76_86f; 5. double d = 1_2_3_4; How many statements are legal?",
    Option_A: "One statement only",
    Option_B: "Two statements only",
    Option_C: "Three statements only",
    Option_D: "Four statements only",
    Option_E: "All 5 statements",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 5,
    Question_ID: "UK8298119",
    Question_Text: "Given code: package com.examtest.ocp; public class Test { public static void main(String[] args) { byte b1 = 10; int i1 = b1; byte b2 = i1; System.out.println(b1 + i1 + b2); } } What is the result?",
    Option_A: "Line n1 causes compilation error",
    Option_B: "Line n2 causes compilation error",
    Option_C: "Line n3 causes compilation error",
    Option_D: "30 is printed on to the console",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 6,
    Question_ID: "UK8295088",
    Question_Text: "Range of short data type is from -32768 to 32767. Which of the following code segments will compile successfully? Choose 3 options.",
    Option_A: "short s1 = 10;",
    Option_B: "short s2 = 32768;",
    Option_C: "final int i3 = 10;short s3 = i3;",
    Option_D: "final int i4 = 40000;short s4 = i4;",
    Option_E: "final int i5 = 10;short s5 = i5 + 100;",
    Option_F: "final int m = 25000;final int n = 25000;short s6 = m + n;",
    Option_G: "int i7 = 10;short s7 = i7;",
    Option_H: "",
    Correct_Answer: "A,C,E"
  },
  {
    Question_Number: 7,
    Question_ID: "UK8297266",
    Question_Text: "Consider below code: package com.examtest.ocp; public class Test { public static void main(String[] args) { boolean b1 = 0; boolean b2 = 1; System.out.println(b1 + b2); } } What is the result?",
    Option_A: "0",
    Option_B: "1",
    Option_C: "true",
    Option_D: "false",
    Option_E: "Compilation error",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 8,
    Question_ID: "UK8298116",
    Question_Text: "Consider below code: package com.examtest.ocp; public class Test { public static void main(String[] args) { Boolean b1 = Boolean.valueOf(\"tRuE\"); Boolean b2 = Boolean.valueOf(\"fAlSe\"); Boolean b3 = Boolean.valueOf(\"abc\"); Boolean b4 = null; System.out.println(b1 + \":\" + b2 + \":\" + b3 + \":\" + b4); } } What is the result?",
    Option_A: "false:false:false:null",
    Option_B: "true:false:false:null",
    Option_C: "false:false:true:null",
    Option_D: "Compilation error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 9,
    Question_ID: "UK8298115",
    Question_Text: "Consider below code with two add methods - one taking double primitives and one taking Double objects. What happens when add(10.0, null) is called?",
    Option_A: "Compilation error",
    Option_B: "double version: 10.0",
    Option_C: "Double version: 10.0",
    Option_D: "An exception is thrown at runtime",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 10,
    Question_ID: "UK8297268",
    Question_Text: "Consider code with overloaded method m accepting Object, Number, and Double. What is printed when m(1) is called?",
    Option_A: "Compilation error",
    Option_B: "Object version",
    Option_C: "Number version",
    Option_D: "Double version",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 11,
    Question_ID: "UK8298594",
    Question_Text: "Consider code: extractInt(2.7); extractInt(2); where extractInt accepts Double. What is the result?",
    Option_A: "22",
    Option_B: "32",
    Option_C: "Compilation error in main method",
    Option_D: "Compilation error in extractInt method",
    Option_E: "An exception is thrown at runtime",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 12,
    Question_ID: "UK8295085",
    Question_Text: "Consider code that iterates through array {\"abc\", \"TrUe\", \"false\", null, \"FALSE\"} and prints T or F based on Boolean.valueOf(s). What is the result?",
    Option_A: "FTFFF",
    Option_B: "FFFFF",
    Option_C: "TTFTT",
    Option_D: "TTTFT",
    Option_E: "NullPointerException is thrown at runtime",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 13,
    Question_ID: "UK8295096",
    Question_Text: "Consider: var x = Math.ceil(10.50) + Math.floor(10.50) + Math.round(10.50); System.out.println(x); What is the result?",
    Option_A: "30.0",
    Option_B: "31.0",
    Option_C: "32.0",
    Option_D: "33.0",
    Option_E: "30",
    Option_F: "31",
    Option_G: "32",
    Option_H: "33",
    Correct_Answer: "C"
  },
  {
    Question_Number: 14,
    Question_ID: "UK8297291",
    Question_Text: "Consider: var x = Double.valueOf(Math.random() * 10).intValue(); Which statement is correct?",
    Option_A: "Output is any int value between 1 and 10",
    Option_B: "Output is any int value between 1 and 9",
    Option_C: "Output is any int value between 0 and 10",
    Option_D: "Output is any int value between 0 and 9",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 15,
    Question_ID: "UK8298141",
    Question_Text: "Consider 3 statements: 1. System.out.println(700 * Math.pow(2, -2)); 2. System.out.println(700 * (1 / 4)); 3. System.out.println(7 * Math.ceil(24.80)); Do all produce same output?",
    Option_A: "Yes",
    Option_B: "No",
    Option_C: "",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 16,
    Question_ID: "UK8297294",
    Question_Text: "Consider: System.out.println(Math.pow(10, Math.____(0.50))); Options: ceil, floor, round, abs. How many produce output 1.0?",
    Option_A: "Only one option",
    Option_B: "Only two options",
    Option_C: "Only three options",
    Option_D: "All four options",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 17,
    Question_ID: "UK8298112",
    Question_Text: "Consider: System.out.println( 53 / 2.0 ); System.out.println( 53 % 2.0 ); What is the result?",
    Option_A: "261",
    Option_B: "26.51.0",
    Option_C: "26.01.0",
    Option_D: "26.50.0",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 18,
    Question_ID: "UK8295086",
    Question_Text: "Consider: System.out.println(\"Password\" + 1 + 2 + 3 + 4); What is the result?",
    Option_A: "Password10",
    Option_B: "Password19",
    Option_C: "Password1234",
    Option_D: "Password 10",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 19,
    Question_ID: "UK8298596",
    Question_Text: "Consider: System.out.println(1 + 2 + 3 + 4 + \"Running\"); What is the result?",
    Option_A: "10Running",
    Option_B: "1234Running",
    Option_C: "64Running",
    Option_D: "10 Running",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 20,
    Question_ID: "UK8297265",
    Question_Text: "Consider: System.out.println(\"1\" + \"2\" + \"3\" == \"1\" + \"2\" + \"3\"); What is the result?",
    Option_A: "Compilation error",
    Option_B: "123",
    Option_C: "true",
    Option_D: "false",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 21,
    Question_ID: "UK8298111",
    Question_Text: "Consider: System.out.println(\"Equals??? \" + 10 != 5); What is the result?",
    Option_A: "Equals??? true",
    Option_B: "Equals??? false",
    Option_C: "Compilation error",
    Option_D: "Equals??? 10 != 5",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 22,
    Question_ID: "UK8295087",
    Question_Text: "Consider: System.out.println(\"Result is: \" + (10 != 5)); What is the result?",
    Option_A: "Result is: true",
    Option_B: "Result is: false",
    Option_C: "Compilation error",
    Option_D: "Result is: (10 != 5)",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 23,
    Question_ID: "UK8297281",
    Question_Text: "Consider byte var = 127; Which options compile when used in System.out.println()? Options: var=var-1, var=var+1, ++var, --var, var*=2, var-=10, var+=2, var. How many compile?",
    Option_A: "One option only",
    Option_B: "Two options only",
    Option_C: "Three options only",
    Option_D: "Four options only",
    Option_E: "Five options only",
    Option_F: "Six options only",
    Option_G: "Seven options only",
    Option_H: "All eight options",
    Correct_Answer: "F"
  },
  {
    Question_Number: 24,
    Question_ID: "UK8297283",
    Question_Text: "Consider String text = null; How many options print nullnullnull? Options include text.repeat(3), null+null+null, null+\"null\"+null, text*=3, text+=\"null\".repeat(2), text+text+text, text+=null;text.concat(null)",
    Option_A: "One option only",
    Option_B: "Two options only",
    Option_C: "Three options only",
    Option_D: "Four options only",
    Option_E: "Five options only",
    Option_F: "Six options only",
    Option_G: "All seven options",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 25,
    Question_ID: "UK8298130",
    Question_Text: "Consider class A with toString() returning null. String text = null; text = text + new A(); System.out.println(text.length()); What is the result?",
    Option_A: "Line n1 causes compilation error",
    Option_B: "Line n1 causes Runtime error",
    Option_C: "Line n2 causes Runtime error",
    Option_D: "0",
    Option_E: "4",
    Option_F: "8",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "F"
  },
  {
    Question_Number: 26,
    Question_ID: "UK8297282",
    Question_Text: "Consider: String text = \"RISE \"; text = text + (text = \"ABOVE \"); System.out.println(text); What is the result?",
    Option_A: "RISE RISE ABOVE",
    Option_B: "RISE ABOVE",
    Option_C: "ABOVE ABOVE",
    Option_D: "RISE ABOVE RISE",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 27,
    Question_ID: "UK8291979",
    Question_Text: "Consider: StringBuilder sb = new StringBuilder(\"INHALE \"); String s = sb.toString() + (sb.append(\"EXHALE \")); System.out.println(s.strip().length()); What is the result?",
    Option_A: "21",
    Option_B: "20",
    Option_C: "28",
    Option_D: "27",
    Option_E: "24",
    Option_F: "23",
    Option_G: "18",
    Option_H: "17",
    Correct_Answer: "B"
  },
  {
    Question_Number: 28,
    Question_ID: "UK8292824",
    Question_Text: "Consider: boolean flag = false; System.out.println((flag = true) | (flag = false) || (flag = true)); System.out.println(flag); What is the result?",
    Option_A: "truefalse",
    Option_B: "falsetrue",
    Option_C: "truetrue",
    Option_D: "falsefalse",
    Option_E: "Compilation error",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 29,
    Question_ID: "UK8291977",
    Question_Text: "Consider: boolean status = true; System.out.println(status = false || status = true | status = false); What is the result?",
    Option_A: "true\\nfalse",
    Option_B: "false\\ntrue",
    Option_C: "true\\ntrue",
    Option_D: "false\\nfalse",
    Option_E: "Compilation error",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 30,
    Question_ID: "UK8291971",
    Question_Text: "Consider: var a=3,b=5,c=7,d=9; boolean res = --a + --b < 1 && c++ + d++ > 1; System.out.printf values. What is the result?",
    Option_A: "a = 2, b = 4, c = 7, d = 9, res = false",
    Option_B: "a = 2, b = 4, c = 8, d = 10, res = false",
    Option_C: "a = 2, b = 4, c = 7, d = 9, res = true",
    Option_D: "a = 2, b = 4, c = 8, d = 10, res = true",
    Option_E: "a = 3, b = 5, c = 8, d = 10, res = false",
    Option_F: "a = 3, b = 5, c = 8, d = 10, res = true",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 31,
    Question_ID: "UK8298129",
    Question_Text: "Consider: int m = 20; int var = --m * m++ + m-- - --m; System.out.println values. What is the result?",
    Option_A: "m = 25var = 363",
    Option_B: "m = 363var = 363",
    Option_C: "m = 18var = 363",
    Option_D: "Compilation error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 32,
    Question_ID: "UK8292822",
    Question_Text: "Consider: int x = 7; boolean res = x++ == 7 && ++x == 9 || x++ == 9; Print x and res. What is the result?",
    Option_A: "x = 10res = true",
    Option_B: "x = 9res = true",
    Option_C: "x = 10res = false",
    Option_D: "Compilation error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 33,
    Question_ID: "UK8292821",
    Question_Text: "Given: int a = 1000; System.out.println(-a++); What is the result?",
    Option_A: "Compilation error",
    Option_B: "-1000",
    Option_C: "-1001",
    Option_D: "999",
    Option_E: "-999",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 34,
    Question_ID: "UK8291975",
    Question_Text: "Given: int i = 2; boolean res = false; res = i++ == 2 || --i == 2 && --i == 2; System.out.println(i); What is the result?",
    Option_A: "2",
    Option_B: "3",
    Option_C: "1",
    Option_D: "Compilation error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 35,
    Question_ID: "UK8292820",
    Question_Text: "Consider: int i = 10; System.out.println(i > 3 != false); What is the result?",
    Option_A: "Compilation error",
    Option_B: "true",
    Option_C: "false",
    Option_D: "null",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 36,
    Question_ID: "UK8297279",
    Question_Text: "Consider boolean flags and expressions with == and != operators. What is the result?",
    Option_A: "Line n1 causes compilation error",
    Option_B: "Line n2 causes compilation error",
    Option_C: "truetrue",
    Option_D: "truefalse",
    Option_E: "falsetrue",
    Option_F: "falsefalse",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 37,
    Question_ID: "UK8298126",
    Question_Text: "Consider: var val = 9; System.out.println(val += 10 - -val-- - --val); What is the result?",
    Option_A: "21",
    Option_B: "22",
    Option_C: "23",
    Option_D: "24",
    Option_E: "25",
    Option_F: "26",
    Option_G: "Compilation error",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 38,
    Question_ID: "UK8297293",
    Question_Text: "Consider: LocalDate date = LocalDate.parse(\"2024-1-01\"); What is the result?",
    Option_A: "2024-01-01",
    Option_B: "2024-1-1",
    Option_C: "2024-1-01",
    Option_D: "An exception is thrown at runtime",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 39,
    Question_ID: "UK8298140",
    Question_Text: "Consider: LocalDate date = LocalDate.of(2025, 9, 31); What is the result?",
    Option_A: "Compilation error",
    Option_B: "An exception is thrown at runtime",
    Option_C: "2025-10-01",
    Option_D: "2025-09-30",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 40,
    Question_ID: "UK8291503",
    Question_Text: "Consider: LocalDate date = LocalDate.of(2024, 9, 6); System.out.println(date); What is the result?",
    Option_A: "2024-9-6",
    Option_B: "2024-09-06",
    Option_C: "2024-6-9",
    Option_D: "2024-06-09",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 41,
    Question_ID: "UK8292834",
    Question_Text: "Consider: LocalDate date = LocalDate.of(2068, 4, 15); System.out.println(date.getMonth() + \":\" + date.getMonthValue()); What is the result?",
    Option_A: "APRIL:3",
    Option_B: "APRIL:4",
    Option_C: "April:3",
    Option_D: "April:4",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 42,
    Question_ID: "UK8292839",
    Question_Text: "Consider newYear and christmas LocalDates. What does isAfter and isBefore return?",
    Option_A: "false:true",
    Option_B: "true:false",
    Option_C: "An exception is thrown at runtime",
    Option_D: "Compilation error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 43,
    Question_ID: "UK8291507",
    Question_Text: "Consider: newYear and eventDate both 2027-01-01. What does isAfter and isBefore return?",
    Option_A: "false:false",
    Option_B: "true:true",
    Option_C: "false:true",
    Option_D: "true:false",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 44,
    Question_ID: "UK8292838",
    Question_Text: "Consider: LocalDate date = LocalDate.parse(\"2028-06-06\"); date.minusDays(10); System.out.println(date); What is the result?",
    Option_A: "2028-05-26",
    Option_B: "2028-05-27",
    Option_C: "2028-06-26",
    Option_D: "2028-06-25",
    Option_E: "2028-06-06",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 45,
    Question_ID: "UK8291981",
    Question_Text: "Consider date1 and date2 both LocalDate.parse(\"1980-03-16\"). What does equals and isEqual return?",
    Option_A: "true : false",
    Option_B: "true : true",
    Option_C: "false : true",
    Option_D: "false : false",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 46,
    Question_ID: "UK8291982",
    Question_Text: "Consider: class MyLocalDate extends LocalDate... What is the result?",
    Option_A: "1980-03-16",
    Option_B: "16-03-1980",
    Option_C: "16-3-1980",
    Option_D: "An exception is thrown at runtime",
    Option_E: "Compilation error",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 47,
    Question_ID: "UK8291985",
    Question_Text: "Consider: LocalDate date = LocalDate.parse(\"1980-03-16\"); System.out.println(date.minusYears(-5)); What is the result?",
    Option_A: "1975-03-16",
    Option_B: "1985-03-16",
    Option_C: "Compilation error",
    Option_D: "Runtime exception",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 48,
    Question_ID: "UK8292832",
    Question_Text: "Consider: joiningDate.withDayOfYear(29) on 2006-03-16. What is the result?",
    Option_A: "2006-03-29",
    Option_B: "2006-01-01",
    Option_C: "2006-01-29",
    Option_D: "None of the other options",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 49,
    Question_ID: "UK8291984",
    Question_Text: "Consider: LocalTime time = LocalTime.of(23, 60); What is the result?",
    Option_A: "23:60",
    Option_B: "00:00",
    Option_C: "00:01",
    Option_D: "Compilation error",
    Option_E: "An exception is thrown at runtime",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 50,
    Question_ID: "UK8298136",
    Question_Text: "Consider: LocalDate obj = new LocalDate(2020, 2, 14); What is the result?",
    Option_A: "2020-02-04",
    Option_B: "2020-02-03",
    Option_C: "Compilation error",
    Option_D: "Runtime exception",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 51,
    Question_ID: "UK8297288",
    Question_Text: "Consider: Period period = Period.of(0, 1000, 0); System.out.println(period); What is the result?",
    Option_A: "P0Y1000M0D",
    Option_B: "p0y1000m0d",
    Option_C: "P1000M",
    Option_D: "p1000m",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 52,
    Question_ID: "UK8298135",
    Question_Text: "Consider: Period period = Period.of(0, 0, 0); System.out.println(period); What is the result?",
    Option_A: "P0Y0M0D",
    Option_B: "p0y0m0d",
    Option_C: "P0D",
    Option_D: "p0d",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 53,
    Question_ID: "UK8298137",
    Question_Text: "Consider: Period period = Period.of(2, 1, 0).ofYears(10).ofMonths(5).ofDays(2); What is the result?",
    Option_A: "P12Y6M2D",
    Option_B: "P2Y1M0D",
    Option_C: "P2Y1M",
    Option_D: "P2D",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 54,
    Question_ID: "UK8298132",
    Question_Text: "Consider: LocalDate date = LocalDate.parse(\"2000-06-25\"); while loop with date.plusDays(-1) not reassigned. How many times does println execute?",
    Option_A: "Compilation error",
    Option_B: "An exception is thrown at runtime",
    Option_C: "System.out.println(date) is executed 6 times",
    Option_D: "System.out.println(date) is executed more than 6 times",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 55,
    Question_ID: "UK8298134",
    Question_Text: "Consider: LocalDate obj = LocalDate.now(); System.out.println(obj.getHour()); Which statement is correct?",
    Option_A: "Code fails to compile",
    Option_B: "Code compiles successfully but throws Runtime exception",
    Option_C: "It will print any int value between 0 and 23",
    Option_D: "It will print any int value between 1 and 24",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 56,
    Question_ID: "UK8297286",
    Question_Text: "Consider: LocalDateTime obj = LocalDateTime.now(); System.out.println(obj.getSecond()); Which statement is correct?",
    Option_A: "Code fails to compile",
    Option_B: "Code compiles successfully but throws Runtime exception",
    Option_C: "It will print any int value between 0 and 59",
    Option_D: "It will print any int value between 1 and 60",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 57,
    Question_ID: "UK8298152",
    Question_Text: "Consider 4 LocalDate objects created with parse and of methods. What does == comparison return?",
    Option_A: "true:false:true",
    Option_B: "false:false:true",
    Option_C: "true:true:true",
    Option_D: "false:false:false",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 58,
    Question_ID: "UK8291516",
    Question_Text: "Consider: LocalDate date = LocalDate.parse(\"1947-08-14\"); LocalTime time = LocalTime.MAX; System.out.println(date.atTime(time)); What is the result?",
    Option_A: "1947-08-14T23:59:59",
    Option_B: "1947-08-14T23:59:59.999",
    Option_C: "1947-08-14T23:59:59.999999999",
    Option_D: "1947-08-14T23:59:59.0",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 59,
    Question_ID: "UK8292848",
    Question_Text: "Consider: date.plus(Period.ofYears(-3000)) on 2000-01-01. What is the result?",
    Option_A: "Compilation error",
    Option_B: "Runtime exception",
    Option_C: "1000-01-01",
    Option_D: "-1000-01-01",
    Option_E: "5000-01-01",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 60,
    Question_ID: "UK8292847",
    Question_Text: "Consider: Period.parse(\"p-30000y\") added to 2000-01-01. What is the result?",
    Option_A: "Compilation error",
    Option_B: "Runtime exception",
    Option_C: "-28000-01-01",
    Option_D: "28000-01-01",
    Option_E: "32000-01-01",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 61,
    Question_ID: "UK8292846",
    Question_Text: "Which gives current system time? Select 2 options.",
    Option_A: "System.out.println(new LocalDate())",
    Option_B: "System.out.println(LocalDate.now())",
    Option_C: "System.out.println(new LocalTime())",
    Option_D: "System.out.println(LocalTime.now())",
    Option_E: "System.out.println(new LocalDateTime())",
    Option_F: "System.out.println(LocalDateTime.now())",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D,F"
  },
  {
    Question_Number: 62,
    Question_ID: "UK8291514",
    Question_Text: "Consider: LocalDate date = LocalDate.parse(\"1983-06-30\"); System.out.println(date.plusMonths(8)); What is the result?",
    Option_A: "1983-02-30",
    Option_B: "1983-02-29",
    Option_C: "1983-02-28",
    Option_D: "1984-02-30",
    Option_E: "1984-02-29",
    Option_F: "1984-02-28",
    Option_G: "An exception is thrown at runtime",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 63,
    Question_ID: "UK8291998",
    Question_Text: "Consider: LocalDate ocpCouponPurchaseDate = LocalDate.of(2023, 3, 1); System.out.println(ocpCouponPurchaseDate.plusDays(10)); What is the result?",
    Option_A: "Coupon expiry date: 2023-3-11",
    Option_B: "Coupon expiry date: 2023-03-11",
    Option_C: "Compilation error",
    Option_D: "Runtime exception",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 64,
    Question_ID: "UK8291999",
    Question_Text: "Consider: LocalDate date = LocalDate.ofYearDay(2022, 32); What is the result?",
    Option_A: "Runtime exception",
    Option_B: "2022-02-01",
    Option_C: "2022-02-02",
    Option_D: "2022-2-1",
    Option_E: "2022-2-2",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 65,
    Question_ID: "UK8292849",
    Question_Text: "Consider: date.plusMonths(-6) on 2020-08-31. What is the result?",
    Option_A: "2020-02-31",
    Option_B: "2020-02-30",
    Option_C: "2020-02-29",
    Option_D: "2020-02-28",
    Option_E: "An exception is thrown at runtime",
    Option_F: "Compilation error",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 66,
    Question_ID: "UK8291993",
    Question_Text: "Consider: LocalDate date = LocalDate.ofEpochDay(0); What is the result?",
    Option_A: "1970-01-01",
    Option_B: "Runtime Exception",
    Option_C: "1970-00-01",
    Option_D: "1970-1-1",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 67,
    Question_ID: "UK8292844",
    Question_Text: "Consider: LocalDate date = LocalDate.ofYearDay(2023, 0); What is the result?",
    Option_A: "2023-01-01",
    Option_B: "2023-1-1",
    Option_C: "2022-12-31",
    Option_D: "Runtime Exception",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 68,
    Question_ID: "UK8291513",
    Question_Text: "Consider: LocalDate date = LocalDate.ofEpochDay(1); What is the result?",
    Option_A: "1970-01-01",
    Option_B: "1970-01-02",
    Option_C: "1970-1-1",
    Option_D: "1970-1-2",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 69,
    Question_ID: "UK8298146",
    Question_Text: "Consider: LocalDate date = LocalDate.ofEpochDay(-1); What is the result?",
    Option_A: "1970-01-01",
    Option_B: "1969-12-31",
    Option_C: "Runtime Exception",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 70,
    Question_ID: "UK8297299",
    Question_Text: "Consider: LocalTime time = LocalTime.parse(\"14:14:59.1111\"); What is the result?",
    Option_A: "Runtime Exception",
    Option_B: "14:14:59.1111",
    Option_C: "14:14:59.111100",
    Option_D: "14:14:59.111100000",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 71,
    Question_ID: "UK8298149",
    Question_Text: "Consider: LocalDateTime dt = LocalDateTime.parse(\"2025-03-16t10:15:30.22\"); What is the result?",
    Option_A: "2025-03-16t10:15:30.22",
    Option_B: "2025-03-16T10:15:30.22",
    Option_C: "2025-03-16t10:15:30.220",
    Option_D: "2025-03-16T10:15:30.220",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 72,
    Question_ID: "UK8298143",
    Question_Text: "Consider: LocalDateTime dt = LocalDateTime.parse(\"2018-03-16t10:15:30.22\"); System.out.println(dt.toLocalDate() + \" \" + dt.toLocalTime()); What is the result?",
    Option_A: "2018-03-16 10:15:30.22",
    Option_B: "2018-03-16 10:15:30.220",
    Option_C: "Compilation error",
    Option_D: "Runtime exception",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 73,
    Question_ID: "UK8297296",
    Question_Text: "Consider: System.out.println(dt.toLocalDate() + dt.toLocalTime()); What is the result?",
    Option_A: "2018-03-1610:15:30.22",
    Option_B: "2018-03-1610:15:30.220",
    Option_C: "Compilation error",
    Option_D: "Runtime exception",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 74,
    Question_ID: "UK8298142",
    Question_Text: "Consider: System.out.println(Instant.EPOCH); What is the result?",
    Option_A: "1970-01-01T00:00:00",
    Option_B: "1970-01-01T00:00:00Z",
    Option_C: "1970-01-01T00:00:00.000",
    Option_D: "1970-01-01T00:00:00.000Z",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 75,
    Question_ID: "UK8297298",
    Question_Text: "Consider: Period.between(endDate, startDate) where dates are March 1 and March 11 2023. What is the result?",
    Option_A: "P10D",
    Option_B: "P11D",
    Option_C: "P-10D",
    Option_D: "P-11D",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 76,
    Question_ID: "UK8297297",
    Question_Text: "Which statement will tell you the period left for 2022 world cup from today?",
    Option_A: "Period.between(LocalDateTime.now(), LocalDateTime.parse(\"2022-11-21\"))",
    Option_B: "Period.between(LocalDateTime.now(), LocalDate.parse(\"2022-11-21\"))",
    Option_C: "Period.between(LocalDate.now(), LocalDateTime.parse(\"2022-11-21\"))",
    Option_D: "Period.between(LocalDate.now(), LocalDate.parse(\"2022-11-21\"))",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 77,
    Question_ID: "UK8291929",
    Question_Text: "Consider: LocalDate.of(2024, 6, 6).plus(Period.parse(\"P9M\")); What is the result?",
    Option_A: "2024-3-6",
    Option_B: "2024-03-06",
    Option_C: "2025-3-6",
    Option_D: "2025-03-06",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 78,
    Question_ID: "UK8291924",
    Question_Text: "Consider: Period period = Period.ofWeeks(100); What is the result?",
    Option_A: "P100W",
    Option_B: "p100w",
    Option_C: "p700d",
    Option_D: "P700D",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 79,
    Question_ID: "UK8291921",
    Question_Text: "Consider: System.out.println(Duration.ofDays(-2)); What is the result?",
    Option_A: "P-2D",
    Option_B: "P2D",
    Option_C: "PT-48H",
    Option_D: "PT48H",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 80,
    Question_ID: "UK8291925",
    Question_Text: "Consider: Duration.between(LocalDate.now(), LocalDateTime.now()); What is the result?",
    Option_A: "Program terminates successfully after displaying the output",
    Option_B: "Compilation error",
    Option_C: "Runtime Exception",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 81,
    Question_ID: "UK8298558",
    Question_Text: "Consider: Duration.between(LocalTime.now(), LocalDateTime.now()); What is the result?",
    Option_A: "Program terminates successfully after displaying the output",
    Option_B: "Compilation error",
    Option_C: "Runtime Exception",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 82,
    Question_ID: "UK8297227",
    Question_Text: "Consider: Duration.between(LocalDateTime.now(), LocalTime.now()); What is the result?",
    Option_A: "Program terminates successfully after displaying the output",
    Option_B: "Compilation error",
    Option_C: "Runtime Exception",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 83,
    Question_ID: "UK8295048",
    Question_Text: "Consider: t1.plus(22, ChronoUnit.HOURS).equals(t1.plusHours(22)); What is the result?",
    Option_A: "Runtime Exception",
    Option_B: "true",
    Option_C: "false",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 84,
    Question_ID: "UK8297226",
    Question_Text: "Consider: date1.minus(Period.ofDays(1)) and date2.plus(Period.ofDays(1)) not reassigned. What does equals and isEqual return?",
    Option_A: "true:true",
    Option_B: "false:false",
    Option_C: "false:true",
    Option_D: "true:false",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 85,
    Question_ID: "UK8298554",
    Question_Text: "Consider: date1.plus(Duration.ofDays(1)) on LocalDate. What is the result?",
    Option_A: "2019-01-02",
    Option_B: "2019-01-01",
    Option_C: "Runtime exception",
    Option_D: "Compilation error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 86,
    Question_ID: "UK8294196",
    Question_Text: "_______ represents date-based amount of time where as _______ represents time-based amount of time.",
    Option_A: "Period, Duration",
    Option_B: "Duration, Period",
    Option_C: "Duration, Instant",
    Option_D: "Instant, Duration",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 87,
    Question_ID: "UK8294195",
    Question_Text: "Which of the following classes support time zone?",
    Option_A: "LocalDate",
    Option_B: "LocalTime",
    Option_C: "LocalDateTime",
    Option_D: "ZonedDateTime",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 88,
    Question_ID: "UK8294194",
    Question_Text: "Daylight saving time ended at 4-Nov-2018 2:00 AM. What is result of adding 1 second to 1:59:59?",
    Option_A: "2:0:0",
    Option_B: "1:0:0",
    Option_C: "3:0:0",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 89,
    Question_ID: "UK8296377",
    Question_Text: "Daylight saving time ended at 4-Nov-2018 2:00 AM. What is result of adding 1 second to 13:59:59?",
    Option_A: "12:0:0",
    Option_B: "13:0:0",
    Option_C: "14:0:0",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 90,
    Question_ID: "UK8296378",
    Question_Text: "Do 2018-02-01T10:30+05:30[Asia/Kolkata] and 2018-01-31T21:00-08:00[America/Los_Angeles] represent same time?",
    Option_A: "Yes",
    Option_B: "No",
    Option_C: "",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 91,
    Question_ID: "UK8298555",
    Question_Text: "To get duration for which Los Angeles citizen has to wait to celebrate new year when it's midnight in India, which method to use?",
    Option_A: "zIndia.withZoneSameLocal(us)",
    Option_B: "zIndia.withZoneSameInstant(us)",
    Option_C: "Cannot be achieved by just replacing /*INSERT*/",
    Option_D: "",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 92,
    Question_ID: "UK8296371",
    Question_Text: "Which statement converts Instant to LocalDateTime?",
    Option_A: "instant.toLocalDateTime()",
    Option_B: "LocalDateTime.of(instant)",
    Option_C: "instant.atZone(ZoneId.systemDefault()).toLocalDateTime()",
    Option_D: "(LocalDateTime)instant",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 93,
    Question_ID: "UK8298550",
    Question_Text: "Which statements convert Date to LocalDate? Choose 2.",
    Option_A: "(LocalDate)date",
    Option_B: "date.toLocalDate()",
    Option_C: "LocalDate.of(date)",
    Option_D: "date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()",
    Option_E: "Instant.ofEpochMilli(date.getTime()).atZone(ZoneId.systemDefault()).toLocalDate()",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D,E"
  },
  {
    Question_Number: 94,
    Question_ID: "UK8298552",
    Question_Text: "Consider: var str = \"Have Faith!\"; System.out.println(str.length() + \" : \" + str.charAt(10)); What is the result?",
    Option_A: "11 : !",
    Option_B: "10 : !",
    Option_C: "An exception is thrown at runtime",
    Option_D: "11 : h",
    Option_E: "10 : h",
    Option_F: "Compilation error",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 95,
    Question_ID: "UK8297221",
    Question_Text: "Which options print true when comparing s1=\"OCP\" and s2=\"ocp\"?",
    Option_A: "s1.equals(s2)",
    Option_B: "s1.equals(s2.toUpper())",
    Option_C: "s2.equals(s1.toLower())",
    Option_D: "s1.length() == s2.length()",
    Option_E: "s1.equalsIgnoreCase(s2)",
    Option_F: "s1.contentEquals(s2)",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D,E"
  },
  {
    Question_Number: 96,
    Question_ID: "UK8294197",
    Question_Text: "Consider: String fName = \"Joshua\"; String lName = \"Bloch\"; System.out.println(fName = lName); What is the result?",
    Option_A: "Compilation error",
    Option_B: "false",
    Option_C: "true",
    Option_D: "None of the other options",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 97,
    Question_ID: "UK8296374",
    Question_Text: "Consider: String str = \"Think\"; change(str); where change does s.concat(\"_Twice\"). What is printed?",
    Option_A: "Think",
    Option_B: "_Twice",
    Option_C: "Think_Twice",
    Option_D: "None of the other options",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 98,
    Question_ID: "UK8295043",
    Question_Text: "Consider: String text = \"ONE \"; System.out.println(text.concat(text.concat(\"ELEVEN \")).trim()); What is the result?",
    Option_A: "ONE ELEVEN",
    Option_B: "ONE ONE ELEVEN",
    Option_C: "ONE ELEVEN ONE ELEVEN",
    Option_D: "ONE ELEVEN ONE",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 99,
    Question_ID: "UK8296390",
    Question_Text: "Which methods remove leading and trailing spaces from \" BE YOURSELF! \" to print \"BE YOURSELF!\"? Choose 3.",
    Option_A: "trim()",
    Option_B: "strip()",
    Option_C: "stripLeading().stripTrailing()",
    Option_D: "ltrim().rtrim()",
    Option_E: "trimLeading().trimTrailing()",
    Option_F: "trimBoth()",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A,B,C"
  },
  {
    Question_Number: 100,
    Question_ID: "UK8298570",
    Question_Text: "Consider: public class Test extends String { ... } What is the result?",
    Option_A: "TEST",
    Option_B: "Output string contains @ symbol",
    Option_C: "Exception is thrown at runtime",
    Option_D: "Compilation error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 101,
    Question_ID: "UK8296391",
    Question_Text: "How many String objects in HEAP when control is at Line n9 after creating s1-s5 with mix of new String and literals?",
    Option_A: "2",
    Option_B: "3",
    Option_C: "4",
    Option_D: "5",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 102,
    Question_ID: "UK8291935",
    Question_Text: "Which extracts country code (characters at index 4 and 5) from swift code?",
    Option_A: "swiftCode.substring(4, 6)",
    Option_B: "swiftCode.substring(5, 6)",
    Option_C: "swiftCode.substring(5, 7)",
    Option_D: "swiftCode.substring(4, 5)",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  },
  {
    Question_Number: 103,
    Question_ID: "UK8291932",
    Question_Text: "Consider: String str = \" \"; What does isEmpty() and isBlank() return before and after strip()?",
    Option_A: "false : truetrue : true",
    Option_B: "false : falsetrue : true",
    Option_C: "true : falsetrue : false",
    Option_D: "false : truefalse : true",
    Option_E: "false : truetrue : false",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 104,
    Question_ID: "UK8291938",
    Question_Text: "Consider: String s1 = \"1Z0-829\"; String s2 = \"1Z0-829\" + \"\"; System.out.println(s1 == s2); What is the result?",
    Option_A: "1Z0-829",
    Option_B: "true",
    Option_C: "false",
    Option_D: "Compilation error",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 105,
    Question_ID: "UK8291936",
    Question_Text: "Consider: final String fName = \"James\"; String lName = \"Gosling\"; What does name1==name2 and name2==name3 return?",
    Option_A: "truetrue",
    Option_B: "truefalse",
    Option_C: "falsefalse",
    Option_D: "falsetrue",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "D"
  },
  {
    Question_Number: 106,
    Question_ID: "UK8298569",
    Question_Text: "Consider: final int i1=1; final Integer i2=1; final String s1=\":ONE\"; What does str1==\"1:ONE\" and str2==\"1:ONE\" return?",
    Option_A: "truetrue",
    Option_B: "truefalse",
    Option_C: "falsefalse",
    Option_D: "falsetrue",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 107,
    Question_ID: "UK8291930",
    Question_Text: "Consider: java += world where java=\"Java\" and world=\"World\". What does java == javaworld return?",
    Option_A: "JavaWorld",
    Option_B: "Java",
    Option_C: "World",
    Option_D: "true",
    Option_E: "false",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 108,
    Question_ID: "UK8291931",
    Question_Text: "Consider: m1(null) with overloaded methods for CharSequence, String, and Object. What is the result?",
    Option_A: "Compilation Error",
    Option_B: "CharSequence",
    Option_C: "String",
    Option_D: "Object",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 109,
    Question_ID: "UK8297234",
    Question_Text: "Which types for x and y print 3 for String.valueOf(x + y).length() where x=7, y=200?",
    Option_A: "byte",
    Option_B: "short",
    Option_C: "int",
    Option_D: "long",
    Option_E: "float",
    Option_F: "double",
    Option_G: "var",
    Option_H: "",
    Correct_Answer: "B,C,D"
  },
  {
    Question_Number: 110,
    Question_ID: "UK8298565",
    Question_Text: "Which options make str=\"*\" become \"*****\"? Choose 2.",
    Option_A: "str.repeat(5);",
    Option_B: "str = str.repeat(5);",
    Option_C: "String.repeat(str, 5);",
    Option_D: "str = String.repeat(str, 5);",
    Option_E: "str *= 5;",
    Option_F: "str = str * 5;",
    Option_G: "for(var var = 0; var < 4; var++) { str += \"*\";}",
    Option_H: "for(int i = 0; i < 5; i++) { str += \"*\";}",
    Correct_Answer: "B,G"
  },
  {
    Question_Number: 111,
    Question_ID: "UK8296388",
    Question_Text: "Consider: final var str = \"+\"; System.out.println(str.repeat(2) == \"++\"); What is the result?",
    Option_A: "true",
    Option_B: "false",
    Option_C: "+",
    Option_D: "++",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 112,
    Question_ID: "UK8297236",
    Question_Text: "Consider: str.replace(\"N\", sb) where str=\"PANIC\" and sb=\"THET\". What is the result?",
    Option_A: "PANIC",
    Option_B: "PATHETIC",
    Option_C: "Line n1 causes compilation error",
    Option_D: "Line n1 throws error at runtime",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 113,
    Question_ID: "UK8298566",
    Question_Text: "Consider: \"Java\" == \"Java\".replace('J', 'J') and \"Java\" == \"Java\".replace(\"J\", \"J\"). What is the result?",
    Option_A: "Line n1 causes compilation error",
    Option_B: "Line n2 causes compilation error",
    Option_C: "true",
    Option_D: "false",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 114,
    Question_ID: "UK8295058",
    Question_Text: "Consider: \"MISSS\".replace(\"SS\", \"T\"); What is the output?",
    Option_A: "MITS",
    Option_B: "MITS",
    Option_C: "MISSS",
    Option_D: "MIT",
    Option_E: "",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 115,
    Question_ID: "UK8295052",
    Question_Text: "Consider: str.charAt(str.indexOf(\"A\") + 1) where str=\"ALASKA\". What is the result?",
    Option_A: "A",
    Option_B: "L",
    Option_C: "S",
    Option_D: "K",
    Option_E: "Runtime error",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 116,
    Question_ID: "UK8298560",
    Question_Text: "Consider: arr[place.indexOf(\"a\", 3)] where place=\"faraway\" and arr={\"1st\",\"2nd\",\"3rd\",\"4th\",\"5th\"}. What is the result?",
    Option_A: "1st",
    Option_B: "3rd",
    Option_C: "5th",
    Option_D: "2nd",
    Option_E: "4th",
    Option_F: "An exception is raised by Line n1",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "E"
  },
  {
    Question_Number: 117,
    Question_ID: "UK8298563",
    Question_Text: "How many options make word=\"REBUS\" print BUS? Options include substring and replace methods.",
    Option_A: "One option only",
    Option_B: "Two options only",
    Option_C: "Three options only",
    Option_D: "Four options only",
    Option_E: "Five options only",
    Option_F: "All 6 options",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 118,
    Question_ID: "UK8295053",
    Question_Text: "Which statements are correct about String.join snippets with null arrays?",
    Option_A: "Snippet 1 compiles successfully",
    Option_B: "Snippet 2 compiles successfully",
    Option_C: "Snippet 3 compiles successfully",
    Option_D: "Snippet 4 compiles successfully",
    Option_E: "Snippet 1 throws runtime exception",
    Option_F: "Snippet 2 throws runtime exception",
    Option_G: "Snippet 3 throws runtime exception",
    Option_H: "Snippet 4 throws runtime exception",
    Correct_Answer: "A,B,C,G"
  },
  {
    Question_Number: 119,
    Question_ID: "UK8296385",
    Question_Text: "Consider: str = String.join(\"-\", str.split(\" \")) where str=\"USER GENERATED\". What is the result?",
    Option_A: "USER GENERATED",
    Option_B: "USER-GENERATED",
    Option_C: "-",
    Option_D: "Compilation error",
    Option_E: "An exception is thrown at runtime",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "B"
  },
  {
    Question_Number: 120,
    Question_ID: "UK8298562",
    Question_Text: "Consider: String.join(\".\", \"BEVERAGE\".split(\"E\", 3)). What is the result?",
    Option_A: "BEVERAGE",
    Option_B: "B.VERAGE",
    Option_C: "B.V.RAGE",
    Option_D: "B.V.RAG.",
    Option_E: "B.V.RAG..",
    Option_F: "Compilation error",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "C"
  },
  {
    Question_Number: 121,
    Question_ID: "UK8298581",
    Question_Text: "Consider: \"an\".split(\"an\").length. What is the result?",
    Option_A: "0",
    Option_B: "1",
    Option_C: "2",
    Option_D: "3",
    Option_E: "Compilation error",
    Option_F: "",
    Option_G: "",
    Option_H: "",
    Correct_Answer: "A"
  }
];
